CREATE OR REPLACE TRIGGER TRG_LIMPIAR_TOKENS_USADOS
AFTER INSERT ON PASSWORD_RESET_TOKENS
BEGIN
    DELETE FROM PASSWORD_RESET_TOKENS
    WHERE usado = 1 OR fecha_expiracion < SYSTIMESTAMP;
    COMMIT;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_SOLICITUDES
AFTER UPDATE OF estado ON SOLICITUD_COMISION
FOR EACH ROW
BEGIN
    IF :OLD.estado != :NEW.estado THEN
        INSERT INTO AUDITORIA_SOLICITUDES (id_comision, id_empleado, estado_anterior, estado_nuevo)
        VALUES (:OLD.id_comision, :OLD.id_empleado, :OLD.estado, :NEW.estado);
    END IF;
END;

/