-- Active: 1766458157960@@127.0.0.1@1521@XE@C
-- PROYECTO: SISTEMA DE GESTIÓN DE VIÁTICOS
-- EMPRESA: Ingeniería y Servicios del Sur S.A.C.
-- DESCRIPCIÓN: Modelo optimizado para escalabilidad de conceptos de gasto.
-- MOTOR: Oracle Database 12c+
-- ESQUEMA: VIATICOS_USER

/*
CREATE USER C##viaticos_user IDENTIFIED BY "admin123";
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE TO C##viaticos_user;
ALTER USER C##viaticos_user QUOTA UNLIMITED ON USERS;
*/

-- ZONAS_GEOGRAFICAS
CREATE TABLE zonas_geograficas (
    id_zona NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_zona VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(200),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1))
);
/
-- NIVELES_JERARQUICOS
CREATE TABLE niveles_jerarquicos (
    id_nivel NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_nivel VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(200),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1))
);
/
-- TIPOS_GASTO
CREATE TABLE tipos_gasto (
    id_tipo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre_gasto VARCHAR2(50) NOT NULL,
    requiere_factura NUMBER(1) DEFAULT 1 CHECK (requiere_factura IN (0, 1)),
    cuenta_contable VARCHAR2(20),
    es_asignable_por_dia NUMBER(1) DEFAULT 1 CHECK (
        es_asignable_por_dia IN (0, 1)
    ),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1))
);
/
-- TARIFARIO_VIATICOS
CREATE TABLE tarifario_viaticos (
    id_tarifa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_zona NUMBER NOT NULL,
    id_nivel NUMBER NOT NULL,
    id_tipo_gasto NUMBER NOT NULL,
    monto_limite_diario NUMBER(10, 2) NOT NULL,
    moneda CHAR(3) DEFAULT 'PEN',
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1)),
    -- Constraints
    CONSTRAINT fk_tarifa_zona FOREIGN KEY (id_zona) REFERENCES zonas_geograficas (id_zona),
    CONSTRAINT fk_tarifa_nivel FOREIGN KEY (id_nivel) REFERENCES niveles_jerarquicos (id_nivel),
    CONSTRAINT fk_tarifa_tipo FOREIGN KEY (id_tipo_gasto) REFERENCES tipos_gasto (id_tipo)
);
/
-- EMPLEADOS
CREATE TABLE empleados (
    id_empleado NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombres VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    dni CHAR(8) NOT NULL UNIQUE,
    email VARCHAR2(100) UNIQUE,
    id_nivel NUMBER NOT NULL,
    cuenta_bancaria VARCHAR2(20),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    -- Constraints
    CONSTRAINT fk_empleado_nivel FOREIGN KEY (id_nivel) REFERENCES niveles_jerarquicos (id_nivel)
);
/
-- SOLICITUD_COMISION
CREATE TABLE solicitud_comision (
    id_comision NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_empleado NUMBER NOT NULL,
    motivo_viaje VARCHAR2(255) NOT NULL,
    fecha_solicitud DATE DEFAULT SYSDATE,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR2(20) DEFAULT 'BORRADOR',
    monto_total NUMBER(12, 2),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    comentario_rechazo VARCHAR2(500),
    -- Constraints
    CONSTRAINT ck_sol_estado CHECK (
        estado IN (
            'BORRADOR',
            'PENDIENTE',
            'APROBADO',
            'RECHAZADO',
            'RENDIDO',
            'LIQUIDADO',
            'CANCELADO',
            'OBSERVADO'
        )
    ),
    CONSTRAINT fk_sol_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado)
);

/
-- ITINERARIO_VIAJE
CREATE TABLE itinerario_viaje (
    id_itinerario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_comision NUMBER NOT NULL,
    id_zona_destino NUMBER NOT NULL,
    ciudad_especifica VARCHAR2(100),
    noches NUMBER NOT NULL,
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    -- Constraints
    CONSTRAINT fk_iti_comision FOREIGN KEY (id_comision) REFERENCES solicitud_comision (id_comision),
    CONSTRAINT fk_iti_zona FOREIGN KEY (id_zona_destino) REFERENCES zonas_geograficas (id_zona)
);
/
-- ASIGNACION_DINERO
CREATE TABLE asignacion_dinero (
    id_asignacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_comision NUMBER NOT NULL UNIQUE,
    monto_calculado_sistema NUMBER(10, 2) NOT NULL,
    monto_real_otorgado NUMBER(10, 2) NOT NULL,
    fecha_deposito DATE,
    numero_operacion_bancaria VARCHAR2(50),
    estado_transferencia VARCHAR2(20) DEFAULT 'PENDIENTE',
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    -- Constraints
    CONSTRAINT ck_asig_estado CHECK (
        estado_transferencia IN ('PENDIENTE', 'COMPLETADO')
    ),
    CONSTRAINT fk_asig_comision FOREIGN KEY (id_comision) REFERENCES solicitud_comision (id_comision)
);
/
-- RENDICION_CUENTAS
CREATE TABLE rendicion_cuentas (
    id_rendicion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_comision NUMBER NOT NULL UNIQUE,
    fecha_presentacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_gastado_bruto NUMBER(10, 2) DEFAULT 0.00,
    total_aceptado NUMBER(10, 2) DEFAULT 0.00,
    comentarios_empleado CLOB,
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    -- Constraints
    CONSTRAINT fk_ren_comision FOREIGN KEY (id_comision) REFERENCES solicitud_comision (id_comision)
);
/
-- DETALLE_COMPROBANTES
CREATE TABLE detalle_comprobantes (
    id_detalle NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_rendicion NUMBER NOT NULL,
    id_tipo_gasto NUMBER NOT NULL,
    fecha_emision DATE NOT NULL,
    tipo_comprobante VARCHAR2(50),
    serie_comprobante VARCHAR2(20),
    numero_comprobante VARCHAR2(30),
    ruc_emisor CHAR(11),
    razon_social_emisor VARCHAR2(150),
    monto_bruto NUMBER(10, 2) DEFAULT 0,
    monto_igv NUMBER(10, 2) DEFAULT 0,
    monto_total NUMBER(10, 2) NOT NULL,
    archivo_url VARCHAR2(255),
    estado VARCHAR2(20) DEFAULT 'PENDIENTE',
    motivo_rechazo VARCHAR2(255),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    -- Constraints
    CONSTRAINT fk_det_rendicion FOREIGN KEY (id_rendicion) REFERENCES rendicion_cuentas (id_rendicion),
    CONSTRAINT fk_det_tipo FOREIGN KEY (id_tipo_gasto) REFERENCES tipos_gasto (id_tipo),
    CONSTRAINT ck_det_estado CHECK (
        estado IN (
            'PENDIENTE',
            'ACEPTADO',
            'RECHAZADO'
        )
    )
);

/
-- LIQUIDACION_FINAL
CREATE TABLE liquidacion_final (
    id_liquidacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_comision NUMBER NOT NULL UNIQUE,
    monto_asignado NUMBER(10, 2) NOT NULL,
    monto_rendido_validado NUMBER(10, 2) NOT NULL,
    saldo_a_favor_empresa NUMBER(10, 2) DEFAULT 0.00,
    saldo_a_favor_empleado NUMBER(10, 2) DEFAULT 0.00,
    fecha_cierre DATE,
    estado_cierre VARCHAR2(20) DEFAULT 'PENDIENTE',
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    -- Constraints
    CONSTRAINT ck_liq_estado CHECK (
        estado_cierre IN (
            'PENDIENTE',
            'FINALIZADO',
            'REEMBOLSADO'
        )
    ),
    CONSTRAINT fk_liq_comision FOREIGN KEY (id_comision) REFERENCES solicitud_comision (id_comision)
);
/

--   SEGURIDAD Y ACCESO

-- ROLES
CREATE TABLE roles (
    id_rol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    codigo_rol VARCHAR2(30) NOT NULL UNIQUE, -- Código interno: ROLE_ADMIN, ROLE_USER
    nombre_rol VARCHAR2(50) NOT NULL, -- Nombre visible: Administrador, Usuario
    descripcion VARCHAR2(100),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1))
);
/
-- USUARIOS
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_empleado NUMBER NOT NULL UNIQUE,
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(200) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    id_rol NUMBER NOT NULL,
    activo NUMBER(1) DEFAULT 1 CHECK (activo IN (0, 1)),
    -- Auditoría
    user_crea VARCHAR2(30) DEFAULT USER,
    fecha_crea TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_mod VARCHAR2(30),
    fecha_mod TIMESTAMP,
    CONSTRAINT fk_usuario_empleado FOREIGN KEY (id_empleado) REFERENCES empleados (id_empleado),
    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES roles (id_rol)
);
/